const TYPE = `[APPOINTMENTS]`;

export default {
    FETCH_START: `${TYPE} FETCH START`,
    FETCH_SUCCESS: `${TYPE} FETCH SUCCESS`,
    FETCH_ERROR: `${TYPE} FETCH ERROR`,

    FETCH_ONE_START: `${TYPE} FETCH ONE START`,
    FETCH_ONE_SUCCESS: `${TYPE} FETCH ONE SUCCESS`,
    FETCH_ONE_ERROR: `${TYPE} FETCH ONE ERROR`,

    FETCH_PENDING_START: `${TYPE} FETCH PENDING START`,
    FETCH_PENDING_SUCCESS: `${TYPE} FETCH PENDING SUCCESS`,
    FETCH_PENDING_ERROR: `${TYPE} FETCH PENDING ERROR`,

    RESERVE_START: `${TYPE} RESERVE START`,
    RESERVE_SUCCESS: `${TYPE} RESERVE SUCCESS`,
    RESERVE_ERROR: `${TYPE} RESERVE ERROR`,

    ACCEPT_START: `${TYPE} ACCEPT START`,
    ACCEPT_SUCCESS: `${TYPE} ACCEPT SUCCESS`,
    ACCEPT_ERROR: `${TYPE} ACCEPT ERROR`,

    CONFIRM_START: `${TYPE} CONFIRM START`,
    CONFIRM_SUCCESS: `${TYPE} CONFIRM SUCCESS`,
    CONFIRM_ERROR: `${TYPE} CONFIRM ERROR`,

    RESET_ERROR: `${TYPE} RESET ERROR`,
}