const TYPE = `[USER]`;

export default {
    FETCH_START: `${TYPE} FETCH START`,
    FETCH_SUCCESS: `${TYPE} FETCH SUCCESS`,
    FETCH_ERROR: `${TYPE} FETCH ERROR`,
    
    UPDATE_IMAGE_START: `${TYPE} UPDATE IMAGE START`,
    UPDATE_START: `${TYPE} UPDATE START`,
    UPDATE_SUCCESS: `${TYPE} UPDATE SUCCESS`,
    UPDATE_ERROR: `${TYPE} UPDATE ERROR`,

    SETUP_INTENT_START: `${TYPE} SETUP INTENT START`,
    SETUP_INTENT_SUCCESS: `${TYPE} SETUP INTENT SUCCESS`,
    SETUP_INTENT_ERROR: `${TYPE} SETUP INTENT ERROR`,

    FETCH_PAYMENT_METHODS_START: `${TYPE} FETCH PAYMENT METHODS START`,
    FETCH_PAYMENT_METHODS_SUCCESS: `${TYPE} FETCH PAYMENT METHODS SUCCESS`,
    FETCH_PAYMENT_METHODS_ERROR: `${TYPE} FETCH PAYMENT METHODS ERROR`,

    RESET_ERROR: `${TYPE} RESET ERROR`,
}