const TYPE = `[REQUIRED DOCUMENTATION]`;

const types = {
    FETCH_START: `${TYPE} FETCH START`,
    FETCH_SUCCESS: `${TYPE} FETCH SUCCESS`,
    FETCH_ERROR: `${TYPE} FETCH ERROR`,

    UPLOAD_START: `${TYPE} UPLOAD START`,
    UPLOAD_SUCCESS: `${TYPE} UPLOAD SUCCESS`,
    UPLOAD_ERROR: `${TYPE} UPLOAD ERROR`,

    RESET_ERROR: `${TYPE} RESET ERROR`,
}

export default types;