name: "[TEST] Deploy to IONOS server"
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "[TEST] Deploy to IONOS server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          script: |
            cd terappy/frontend-test/therappy-app/
            git pull origin develop
            nvm use 16
            npm i && CI=false
            npm run build-test
            rsync -a ~/terappy/frontend-test/therappy-app/build /var/www/test.terappy.mx/html
            echo 'Deployment to IONOS server finished'
